### ISSUE TITLE
Syntax error in generated code

### ISSUE THREAD

**Issue by cblp** [ivan-m/graphviz#6]
```haskell
import Data.GraphViz
import Data.GraphViz.Types.Monadic

main :: IO ()
main = do
    let n = [] :: Attributes
        g = digraph' $ node' n
    _ <- runGraphviz g DotOutput "/dev/stdout"
    pure ()
```
gives
```
Test.hs: Error running utility program: Error messages from dot:
Error: .../graphviz16807282475249.gv: syntax error in line 1 near '['
```

**Comment by ivan-m** [comment]
So, working through what's happening here:

`node' :: n -> Dot n`, so with `node' ([] :: Attributes)` you're making a Dot graph where the node type is a list of attributes, which is almost definitely wrong.  More specifically, you're saying that the node identifier is an empty list of attributes, which doesn't really make sense.

(This isn't really a problem with monadic graphs, but with the fact that the 'PrintDot' class really needs to be split into multiple classes, such that an arbitrary list isn't permitted to be used in scenarios like this.  Note that the same problem will almost definitely occur if you used the empty `String` for the node name.)

**Comment by cblp** [comment]
> you're making a Dot graph where the node type is a list of attributes, which is almost definitely wrong

Why?

> you're saying that the node identifier is an empty list of attributes, which doesn't really make sense.

Does `n = [] :: [Int]` make sense? It doesn't trigger the error. Does `n = [textLabel "bug"]` make sense? It *does* trigger the error.

**Comment by ivan-m** [comment]
So the [Dot language specification](http://graphviz.org/content/dot-language) says that a node is either (possibly quoted) String or a number.

The reason it happens to work for `[Int]` is that the `PrintDot` instance for it uses quotes for non-singleton lists (thus producing the String `"[]"), whereas for `[Attribute]` it doesn't use quotes (but according to the specification it should have quotes if used as a label).

So this error occurs because of the fact that I conflated code printing and value printing in the typeclasses.  As such, the types _allow_ you to do this, when according to the specification the values produced are invalid.

In terms of "making sense", I guess I was asking "How is an empty list of attributes a valid identifier for a node?"

**Comment by cblp** [comment]
Why `Dot` type parameter should go to the graphviz node name? When I create graph with fgl's `Data.Graph.Inductive.NodeMap` node names are just autoincrementing integers, and it works perfect.

Or is `Data.GraphViz.Types.Monadic` the means to control node names in output dot code? In such case why don't you just introduce something like PrintDotNodeName such as `PrintDotNodeName n => PrintDot (Generalised.DotGraph n)`?

**Comment by cblp** [comment]
Let me draw my case. I read `n` in `Dot n` type as something identifying a node. For me, a set of attributes (type `Attributes = [Attribute]`) perfectly identify a node. I don't get why I get runtime error. With fgl I can do it without runtime error.

**Comment by ivan-m** [comment]
Sorry I haven't gotten back to you in a while; I was moving and forgot to get back to this :s

The `n` parameter is used to denote the type identifying a node.  Problem is, is that when I rewrote the printing and parsing of Dot code a while back, I conflated top-level terms and individual item terms.

So an `Attribute` or even a list of them is a valid item term, but _not_ as a stand-alone top-level term (well, an individual `Attribute` can be used as a stand-alone top-level term, but not as a node value).

This is admittedly a limitation on my end, and I will be re-writing the printing and parsing code at some time in the future, but not any time soon.

(That said, I'm not sure what you mean by a set of attributes perfectly identifying a node; for actual Dot code you'd need to quote the entire list of attributes rather than use them as-is to be able to use it as a node identifier.)
